import {assertWrap, check} from '@augment-vir/assert';
import {
    ensureError,
    extractErrorMessage,
    getEnumValues,
    getObjectTypedKeys,
    HttpMethod,
    HttpStatus,
    isErrorHttpStatus,
    randomString,
    type SelectFrom,
} from '@augment-vir/common';
import fastifyWs from '@fastify/websocket';
import {
    matchUrlToService,
    type BaseSearchParams,
    type MinimalService,
} from '@rest-vir/define-service';
import {
    RestVirHandlerError,
    ServiceImplementation,
    type GenericServiceImplementation,
    type PostHookParams,
    type RunningServerInfo,
} from '@rest-vir/implement-service';
import {type FastifyInstance} from 'fastify';
import {buildUrl, parseUrl} from 'url-vir';
import {type HandleRouteOptions} from '../handle-request/endpoint-handler.js';
import {handleRoute} from '../handle-request/handle-route.js';
import {preHandler} from '../handle-request/pre-handler.js';
import {setResponseHeaders} from '../util/headers.js';

declare module 'fastify' {
    interface FastifyRequest {
        restVirContext:
            | {
                  /**
                   * {@link attachService} can be called multiple times. Each time it is called, a
                   * new `AttachId` is generated and contexts generated by that attachment are
                   * stored in the request under that id.
                   */
                  [AttachId in string]: {
                      context: unknown;
                      requestData: unknown;
                      protocols: string[];
                      searchParams: BaseSearchParams;
                  };
              }
            | undefined;
    }
}

const endpointFastifyMethods = getEnumValues(HttpMethod).filter((value) => {
    return (
        /** Fastify doesn't support the CONNECT method. */
        value !== HttpMethod.Connect &&
        /** We use the GET method in a separate handler so it can handle WebSocket requests as well. */
        value !== HttpMethod.Get
    );
});

/**
 * Attach all handlers for a {@link ServiceImplementation} to any existing Fastify server.
 *
 * @category Run Service
 * @category Package : @rest-vir/run-service
 * @example
 *
 * ```ts
 * import fastify from 'fastify';
 *
 * const server = fastify();
 *
 * attachService(service, myServiceImplementation);
 *
 * await server.listen({port: 3000});
 * ```
 *
 * @package [`@rest-vir/run-service`](https://www.npmjs.com/package/@rest-vir/run-service)
 */
export async function attachService(
    server: Readonly<FastifyInstance>,
    service: Readonly<
        SelectFrom<
            GenericServiceImplementation,
            {
                webSockets: true;
                endpoints: true;
                serviceName: true;
                createContext: true;
                serviceOrigin: true;
                requiredClientOrigin: true;
                logger: true;
                postHook: true;
            }
        >
    >,
    options: Readonly<HandleRouteOptions> = {},
): Promise<void> {
    try {
        const attachId = randomString(32);

        if (!server.hasRequestDecorator('restVirContext')) {
            server.decorateRequest('restVirContext');
        }
        if (!server.hasRequestDecorator('ws')) {
            await server.register(fastifyWs, {
                /* node:coverage ignore next 14: edge case handling */
                errorHandler(error, webSocket, request) {
                    service.logger.error(
                        new RestVirHandlerError(
                            {
                                isEndpoint: false,
                                isWebSocket: true,
                                path: request.originalUrl,
                                service,
                            },
                            extractErrorMessage(error),
                        ),
                    );
                    webSocket.terminate();
                },
            });
        }

        server.addHook('preValidation', async (request, response) => {
            try {
                return await preHandler(
                    request,
                    response,
                    service,
                    extractRunningServerInfo(service, server),
                    attachId,
                );
            } catch (error) {
                service.logger.error(ensureError(error));
                if (options.throwErrorsForExternalHandling) {
                    throw error;
                } else if (!response.sent) {
                    response.statusCode = HttpStatus.InternalServerError;
                    response.send();
                }
            }
        });
        const postHook = service.postHook;
        if (postHook) {
            server.addHook('onSend', async (request, response, body) => {
                /* node:coverage ignore next 4 */
                const restVirContext = request.restVirContext?.[attachId];
                if (!restVirContext) {
                    return undefined;
                }

                const context = restVirContext.context;
                const requestData = restVirContext.requestData;
                const searchParams = restVirContext.searchParams;

                const pathMatch = matchUrlToService(service, request.originalUrl);

                /* node:coverage ignore next 10 */
                if (!pathMatch) {
                    return undefined;
                }
                const endpointDefinition = pathMatch.endpointPath
                    ? service.endpoints[pathMatch.endpointPath]
                    : undefined;
                const webSocketDefinition =
                    request.ws && pathMatch.webSocketPath
                        ? service.webSockets[pathMatch.webSocketPath]
                        : undefined;

                const postHookParams: PostHookParams = {
                    context,
                    method: assertWrap.isEnumValue(request.method.toUpperCase(), HttpMethod),
                    request,
                    requestData,
                    requestHeaders: request.headers,
                    response,
                    service,
                    endpointDefinition: endpointDefinition,
                    webSocketDefinition: webSocketDefinition,
                    server: extractRunningServerInfo(service, server),
                    searchParams,
                    originalResponseData: body,
                    originalStatus: response.statusCode,
                };

                const result = await postHook(postHookParams);

                if (result) {
                    if (result.headers) {
                        setResponseHeaders(response, result.headers);
                    }
                    if (result.dataType) {
                        setResponseHeaders(response, {
                            'content-type': result.dataType,
                        });
                    }

                    if (result.statusCode) {
                        response.status(result.statusCode);
                    }

                    if (
                        isErrorHttpStatus(result.statusCode ?? response.statusCode) &&
                        'responseErrorMessage' in result
                    ) {
                        if (result.responseErrorMessage == undefined) {
                            /** Clear the body. */
                            return null;
                        } else {
                            return result.responseErrorMessage;
                        }
                    } else if ('responseData' in result) {
                        if (result.responseData == undefined) {
                            /** Clear the body. */
                            return null;
                        } else {
                            return result.responseData;
                        }
                    }
                }

                return undefined;
            });
        }

        const allPaths = new Set([
            ...getObjectTypedKeys(service.webSockets),
            ...getObjectTypedKeys(service.endpoints),
        ]);

        allPaths.forEach((path) => {
            const webSocketDefinition = service.webSockets[path];
            const endpoint = service.endpoints[path];

            if (endpoint && webSocketDefinition) {
                server.route({
                    method: endpointFastifyMethods,
                    url: path,
                    handler(request, response) {
                        return handleRoute(
                            undefined,
                            request,
                            response,
                            endpoint,
                            attachId,
                            extractRunningServerInfo(service, server),
                            options,
                        );
                    },
                });
                server.route({
                    method: HttpMethod.Get,
                    url: path,
                    handler(request, response) {
                        return handleRoute(
                            undefined,
                            request,
                            response,
                            endpoint,
                            attachId,
                            extractRunningServerInfo(service, server),
                            options,
                        );
                    },
                    wsHandler(webSocket, request) {
                        return handleRoute(
                            webSocket,
                            request,
                            undefined,
                            webSocketDefinition,
                            attachId,
                            extractRunningServerInfo(service, server),
                            options,
                        );
                    },
                });
            } else if (endpoint) {
                server.route({
                    method: [
                        ...endpointFastifyMethods,
                        HttpMethod.Get,
                    ],
                    url: path,
                    handler(request, response) {
                        return handleRoute(
                            undefined,
                            request,
                            response,
                            endpoint,
                            attachId,
                            extractRunningServerInfo(service, server),
                            options,
                        );
                    },
                });
            } else if (webSocketDefinition) {
                server.route({
                    method: HttpMethod.Get,
                    url: path,
                    handler(request, response) {
                        return response.status(HttpStatus.NotFound).send();
                    },
                    wsHandler(webSocket, request) {
                        return handleRoute(
                            webSocket,
                            request,
                            undefined,
                            webSocketDefinition,
                            attachId,
                            extractRunningServerInfo(service, server),
                            options,
                        );
                    },
                });
            }
        });

        /* node:coverage ignore next 4: this is just here to cover edge cases. */
    } catch (error) {
        service.logger.error(ensureError(error));
        throw error;
    }
}

/**
 * Merge the running Fastify server's port with the given service's origin port (if it has a port).
 *
 * @category Internal
 */
export function extractRunningServerInfo(
    service: Readonly<Pick<MinimalService, 'serviceOrigin'>>,
    fastify: Readonly<
        SelectFrom<
            FastifyInstance,
            {
                server: {
                    address: true;
                };
            }
        >
    >,
): RunningServerInfo {
    const address = fastify.server.address();

    const {port: originalPort} = parseUrl(service.serviceOrigin);

    if (!originalPort || check.isString(address) || !address) {
        return {
            serviceOrigin: service.serviceOrigin,
        };
    } else {
        const {origin} = buildUrl(service.serviceOrigin, {
            port: address.port,
        });

        return {
            serviceOrigin: origin,
        };
    }
}
