import {
    mapObjectValues,
    type MaybePromise,
    type Overwrite,
    type PartialWithUndefined,
    type Values,
} from '@augment-vir/common';
import {type EndpointDefinition, type GenericEndpointDefinition} from '../endpoint/endpoint.js';
import {type ServiceDefinition} from '../service/service-definition.js';
import {createMockEndpointFetch, createMockEndpointResponse} from '../util/mock-fetch.js';
import {type CommonWebSocket} from '../web-socket/common-web-socket.js';
import {
    type ClientWebSocket,
    type GenericConnectWebSocketParams,
} from '../web-socket/overwrite-web-socket-methods.js';
import {type WebSocketDefinition} from '../web-socket/web-socket-definition.js';
import {type CollapsedConnectWebSocketParams, connectWebSocket} from './connect-web-socket.js';
import {
    type CollapsedFetchEndpointParams,
    fetchEndpoint,
    type FetchEndpointOutput,
    type GenericFetchEndpointParams,
} from './fetch-endpoint.js';

/**
 * An API generated by {@link generateApi}. This can be easily mocked by wrapping this API in
 * {@link makeMockApi}.
 *
 * @category Internal
 * @category Package : @rest-vir/define-service
 * @package [`@rest-vir/define-service`](https://www.npmjs.com/package/@rest-vir/define-service)
 */
export class RestVirApi<SpecificService extends ServiceDefinition> {
    /**
     * All supported endpoints within this API. Use `.fetch()` on an individual endpoint to send
     * requests to it.
     */
    public readonly endpoints: {
        [EndpointPath in keyof SpecificService['endpoints']]: SpecificService['endpoints'][EndpointPath] extends GenericEndpointDefinition
            ? SpecificService['endpoints'][EndpointPath] & {
                  /** Send a fetch request to this endpoint. */
                  fetch(
                      ...params: CollapsedFetchEndpointParams<
                          SpecificService['endpoints'][EndpointPath]
                      >
                  ): Promise<FetchEndpointOutput<SpecificService['endpoints'][EndpointPath]>>;
              }
            : never;
    };
    /**
     * All supported WebSockets within this API. Use `.connect()` on an individual WebSocket to open
     * up connections to it.
     */
    public readonly webSockets: {
        [WebSocketPath in keyof SpecificService['webSockets']]: SpecificService['webSockets'][WebSocketPath] extends WebSocketDefinition
            ? SpecificService['webSockets'][WebSocketPath] & {
                  /** Connect to this WebSocket. */
                  connect(
                      ...params: CollapsedConnectWebSocketParams<
                          SpecificService['webSockets'][WebSocketPath],
                          false
                      >
                  ): Promise<ClientWebSocket<SpecificService['webSockets'][WebSocketPath]>>;
              }
            : never;
    };

    /**
     * Where this API is hosted. This can be freely modified at any time and it will immediately
     * affect all `endpoint.fetch()` and `webSocket.connect()` methods.
     *
     * @example 'https://example.com' 'http://localhost:3000'
     *
     * @see https://developer.mozilla.org/en-US/docs/Web/API/Location for help on which part of the URL is the origin (if necessary).
     */
    public serviceOrigin: string;

    constructor(
        service: SpecificService,
        {endpointFetch, webSocketConnect, serviceOrigin}: Readonly<GenerateApiOptions> = {},
    ) {
        this.serviceOrigin = serviceOrigin || service.serviceOrigin;

        this.endpoints = mapObjectValues(service.endpoints, (endpointPath, endpointDefinition) => {
            return {
                ...endpointDefinition,
                fetch: (...params: CollapsedFetchEndpointParams<EndpointDefinition>) => {
                    return fetchEndpoint(
                        {
                            ...endpointDefinition,
                            service: {
                                ...endpointDefinition.service,
                                serviceOrigin: this.serviceOrigin,
                            },
                        },
                        {
                            ...endpointFetch,
                            ...params[0],
                        },
                    );
                },
            };
        }) as any;
        this.webSockets = mapObjectValues(
            service.webSockets,
            (webSocketPath, webSocketDefinition) => {
                return {
                    ...webSocketDefinition,
                    connect: (
                        ...params: CollapsedConnectWebSocketParams<WebSocketDefinition, false>
                    ) => {
                        return connectWebSocket(
                            {
                                ...webSocketDefinition,
                                service: {
                                    ...webSocketDefinition.service,
                                    serviceOrigin: this.serviceOrigin,
                                },
                            },
                            {
                                ...webSocketConnect,
                                ...params[0],
                            },
                        );
                    },
                };
            },
        ) as any;
    }
}

/**
 * Options for {@link generateApi}.
 *
 * @category Internal
 * @category Package : @rest-vir/define-service
 * @package [`@rest-vir/define-service`](https://www.npmjs.com/package/@rest-vir/define-service)
 */
export type GenerateApiOptions = Readonly<
    PartialWithUndefined<{
        endpointFetch: Readonly<Pick<GenericFetchEndpointParams, 'options' | 'fetch'>>;
        webSocketConnect: Readonly<
            Pick<
                GenericConnectWebSocketParams<CommonWebSocket>,
                'listeners' | 'protocols' | 'webSocketConstructor'
            >
        >;
        /** Override the service definition's service origin. */
        serviceOrigin: string;
    }>
>;

/**
 * Creates an API from the given service definition, with automatically generated endpoint fetch and
 * WebSocket connect methods.
 *
 * Use this to ship auto-generated API objects to internal or external teams so they have type safe
 * access to your REST and WebSocket server.
 *
 * The generated API can easily mocked by wrapping it in {@link makeMockApi}.
 *
 * @category Create API
 * @category Package : @rest-vir/define-service
 * @example
 *
 * ```ts
 * import {generateApi} from '@rest-vir/define-service';
 *
 * export const myApi = generateApi(myServiceDefinition);
 *
 * myApi.endpoints['/my-endpoint'].fetch();
 * myApi.webSockets['/my-web-socket'].connect();
 * ```
 *
 * @package [`@rest-vir/define-service`](https://www.npmjs.com/package/@rest-vir/define-service)
 */
export function generateApi<const SpecificService extends ServiceDefinition>(
    service: SpecificService,
    options: Readonly<GenerateApiOptions> = {},
): RestVirApi<SpecificService> {
    return new RestVirApi<SpecificService>(service, options);
}

/**
 * Mock inputs for {@link makeMockApi}.
 *
 * @category Internal
 * @category Package : @rest-vir/define-service
 * @package [`@rest-vir/define-service`](https://www.npmjs.com/package/@rest-vir/define-service)
 */
export type RestVirApiMocks<
    Api extends RestVirApi<any>,
    WebSocketClass extends CommonWebSocket,
> = PartialWithUndefined<{
    /**
     * A custom fetch mock that will override the default, if provided. This can safely be omitted
     * to use the default JavaScript built-in global `fetch` function.
     *
     * See {@link createMockEndpointFetch} or {@link createMockEndpointResponse} for assistance
     * mocking this.
     *
     * @default globalThis.fetch
     */
    fetch?: (
        url: string,
        requestInit: RequestInit,
        endpoint?: Values<Api['endpoints']> | undefined,
    ) => MaybePromise<Response>;
    webSocketConstructor?: GenericConnectWebSocketParams<WebSocketClass>['webSocketConstructor'];
}>;

/**
 * Overwrites types for an existing {@link RestVirApi} instance with mocks. This is created by
 * {@link makeMockApi}.
 *
 * @category Internal
 * @category Package : @rest-vir/define-service
 * @package [`@rest-vir/define-service`](https://www.npmjs.com/package/@rest-vir/define-service)
 */
export type MockExistingApi<
    Api extends RestVirApi<any>,
    WebSocketClass extends CommonWebSocket,
> = Overwrite<
    Api,
    {
        webSockets: {
            [WebSocketPath in keyof Api['webSockets']]: Api['webSockets'][WebSocketPath] extends WebSocketDefinition
                ? Overwrite<
                      Api['webSockets'][WebSocketPath],
                      {
                          /** Connect to this WebSocket. */
                          connect(
                              ...params: CollapsedConnectWebSocketParams<
                                  Api['webSockets'][WebSocketPath],
                                  false,
                                  WebSocketClass
                              >
                          ): Promise<
                              ClientWebSocket<Api['webSockets'][WebSocketPath], WebSocketClass>
                          >;
                      }
                  >
                : never;
        };
    }
>;

/**
 * Overwrites a generated API's fetch and WebSocket connect methods with a mocked fetch function and
 * a mocked WebSocket constructor so you can have full control over them for unit-testing purposes.
 *
 * With this, you can unit test your clients without spinning up a mock API server.
 *
 * @category Testing : Client (Frontend)
 * @category Package : @rest-vir/define-service
 * @package [`@rest-vir/define-service`](https://www.npmjs.com/package/@rest-vir/define-service)
 */
export function makeMockApi<
    const Api extends RestVirApi<any>,
    const WebSocketClass extends CommonWebSocket,
>(
    api: Readonly<Api>,
    mocks: RestVirApiMocks<Api, WebSocketClass>,
): MockExistingApi<Api, WebSocketClass> {
    return {
        endpoints: mapObjectValues(api.endpoints, (endpointPath, endpointDefinition) => {
            return {
                ...endpointDefinition,
                fetch: (...params: CollapsedFetchEndpointParams<EndpointDefinition>) => {
                    return fetchEndpoint(endpointDefinition as EndpointDefinition, {
                        fetch: mocks.fetch as GenericFetchEndpointParams['fetch'],
                        ...params[0],
                    });
                },
            };
        }),
        webSockets: mapObjectValues(api.webSockets, (webSocketPath, webSocketDefinition) => {
            return {
                ...webSocketDefinition,
                connect: (
                    ...params: CollapsedConnectWebSocketParams<
                        WebSocketDefinition,
                        false,
                        WebSocketClass
                    >
                ) => {
                    return connectWebSocket(webSocketDefinition as WebSocketDefinition, {
                        webSocketConstructor: mocks.webSocketConstructor,
                        ...params[0],
                    });
                },
            };
        }),
    } as unknown as MockExistingApi<Api, WebSocketClass>;
}
